name: PlayerDB
version: '${project.version}'
main: com.mclawa.playerdb.PlayerDB
api-version: 1.19
authors: [ jingwenMC ]
description: PlayerDB - Database and storage Assistant
website: dev.mclawa.com
